title: Stackbit Podcaster Theme
baseURL: /
params:
  layout_type: boxed
  style: bold
  palette: red
  mode: dark
  base_font: sans-serif
  header:
    type: header
    title: Podcaster
    logo: images/logo.svg
    logo_alt: Podcaster logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        label: Episodes
        url: /episodes
        style: link
      - type: action
        label: About
        url: /about
        style: link
      - type: action
        label: Sponsoring
        url: /advertising
        style: link
    has_secondary_nav: true
    secondary_nav_links: []
    has_anncmnt: true
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
      More](/pricing/)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-episode
  footer:
    type: footer
    logo: images/logo.svg
    logo_alt: Podcaster logo
    has_primary_nav: true
    primary_nav_links:
      - type: action
        label: Post
        url: /episodes
        style: link
      - type: action
        label: Subscribe
        url: /subscribe
        style: link
      - type: action
        label: Advertising
        url: /advertising
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        label: About
        url: /about
        style: link
      - type: action
        label: Terms
        url: /terms-conditions
        style: link
      - type: action
        label: Privacy Policy
        url: /privacy-policy
        style: link
    has_tertiary_nav: false
    has_social: true
    social_links:
      - type: action
        label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - type: action
        label: Facebook
        url: 'https://www.facebook.com/'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - type: action
        label: Instagram
        url: 'https://www.instagram.com/'
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=podcaster&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://beige-neptune-9aeee.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
